services:
  timer_site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timer_site_main
    networks:
      - nawah
    ports:
      - "8080:80"
    depends_on:
      - timer_api
    restart: unless-stopped

  timer_api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: timer_api_main
    networks:
      - nawah
    volumes:
      - ./data:/app/data
    restart: unless-stopped

networks:
  nawah:
    external: true
