services:
  timer_site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timer_site_dev
    networks:
      - nawah
    ports:
      - "3001:3000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

networks:
  nawah:
    external: true
