services:
  timer_site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timer_site_main
    networks:
      - nawah
    ports:
      - "8080:80"
    restart: unless-stopped

networks:
  nawah:
    external: true
