services:
  nawah_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nawah_monolith
    networks:
      - nawah
    ports:
      - "3000:3000" # Backend API
    volumes:
      - ./data:/app/data
    restart: unless-stopped

networks:
  nawah:
    external: true
